apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: code-pipeline # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "Add custom code to SAP AI Core"
    scenarios.ai.sap.com/name: "Code (Tutorial) - Wand"
    executables.ai.sap.com/description: "Trains model on median house prices"
    executables.ai.sap.com/name: "House Price (Sklearn) - Wand"
  labels:
    scenarios.ai.sap.com/id: "learning-code"
    ai.sap.com/version: "2.0"
spec:
  imagePullSecrets:
    - name: va-hub # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1

  - name: mycodeblock1
    container:
      image: docker.io/wandproject/house-price:latest # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/main.py"
