apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ssf-extended-model-v1  # Executable id, must be unique across all your workflows (YAML files)
  labels:
    scenarios.ai.sap.com/id: "ssf-extended-model"
    ai.sap.com/version: "1.0"
  annotations:
    scenarios.ai.sap.com/name: "Store Sales - Model (ext)"
    scenarios.ai.sap.com/description: "Create a model (ext)"
    
    executables.ai.sap.com/name: "Model [create] (ext)"
    executables.ai.sap.com/description: "Generate a model (ext)"
    
    artifacts.ai.sap.com/housedataset.kind: "dataset" # Helps in suggesting the kind of artifact that can be attached.
    artifacts.ai.sap.com/housemodel.kind: "model" # Helps in suggesting the kind of artifact that can be generated.

spec:
  imagePullSecrets:
    - name: wand-docker  # Docker registry secret
  entrypoint: mypipeline
  
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1
  - name: mycodeblock1
    
    inputs:
      artifacts:  # placeholder for cloud storage attachements
        - name: store_dataset # a name for the placeholder
          path: /app/data/ # where to copy in the Dataset in the Docker image
    outputs:
      artifacts:
        - name: ssf_ext_finished # name of the artifact generated, and folder name when placed in S3, complete directory will be `../<executaion_id>/housepricemodel`
          globalName: ssf-ext-finished-model # local identifier name to the workflow, also used above in annotation
          path: /app/model/ # from which folder in docker image (after running workflow step) copy contents to cloud storage
          archive:
            none:   # specify not to compress while uploading to cloud
              {}
    
    container:
      image: docker.io/wandproject/ssf-extended:01  # Docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/main/main.py"
